### ISSUE TITLE
If printed with little infill, the shell corner breaks easily under outer pressure

### ISSUE THREAD

**Issue by timmwille** [case06/upklib_v2#2]
New design aspect for the outer corner frame parts
https://github.com/case06/upklib_v2/blob/master/frameset/shell_corner10n_xrot.fcstd

 ![](https://i.imgur.com/OWfkxsy.jpg)

**Comment by timmwille** [comment]
I suggest some good advice for creating a proper gcode file, with thicker wall or solid infill :)

Just a little, but maybe helpfull improvement.

**Comment by Gretel5X** [comment]
I printed it with PLA, 220°C, 4mm Nozzle, 20% Rectilinear Infill and 4 Perimiters. To provide Gcode doesn't make sense since it is individual for every printer (offsets, bed limits, fan power etc). As long as it is not taking any strong mechanical force parallel to the layers, this should be sufficient. Try higher temperatur and less cool for better adhesion if neccessary and/or more perimeters. Infill does not really matter here

**Comment by timmwille** [comment]
Ok, I testet the new print test of @Gretel5X → these printsettings look good, I'll close this as solved, but maybe we can include this in the documentation somewhere... 
![IMG_20200204_204714_6](https://user-images.githubusercontent.com/8081055/73781268-39466980-4790-11ea-88b2-2490d078716c.jpg)

**Comment by case06** [comment]
This looks good.

One can make the parts more stable by increasing the infill-percentage, but setting more perimeter is also a good option because material-saving.

**Comment by Gretel5X** [comment]
A very nice review on part strength:
https://www.youtube.com/watch?v=AmEaNAwFSfI
